### PR TITLE
Update cameraSensors.db

### PR DESCRIPTION
**Pull request by dkudos**
Adding support for the LG-V30.  This is the model I own and tested.  Passes Camera init test.  I am not able to complete render as I do not have an nvidia card that is cuda capable to try.  Here is sony spec for the camera: https://www.sony-semicon.co.jp/products_en/IS/sensor1/img/products/ProductBrief_IMX351_20171109.pdf

Also this is for the main camera only not the wide camera

## Description
Adding support for LG-V30 Phone Main Rear camera.  This is not for the rear wide camera and is not useful for this type of application.

## Features list

Adds support for the LG-V30 main rear camera

## Implementation remarks

Let me know if I should run more testing with a full render.  I just do not have an nvidia card at the moment.  As I have said before this was tested on Linux Mint 18 (Ubuntu) and all the init camera tests passed and it got to cuda section and could not proceed as this computer I have does not have nvidia chipset.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Thanks for the detailed PR and the ref to the documentation.
In your reference of the Sony IMX351 chip, it's written:
`Chip size: 5.893 mm (H) x 4.381 mm (V)`

The size we need in the database is the sensor width (the largest side of sensor size). In this case: it should be `5.893`.
Could you update your commit?

**Comment by fabiencastan** [comment]
The difference is really small here, so it should not have an impact, but it's better to use the right value.

**Comment by dkudos** [comment]
Agreed I misunderstood.  I will update and resubmit.  Love this project.

**Comment by dkudos** [comment]
I have resubmitted and all checks pass.  Let me know if you need anything else.

**Comment by fabiencastan** [comment]
Thanks!

**Pull request merged**
