### PR TITLE
Fix: missing declaration of logging functions in MOSEK

### PR DESCRIPTION
**Pull request by italic-r**
## Description
Logging functions were missing declarations and one usage was missing a closing paren (with minor spelling fix).

Still missing a fix for `error: control reaches end of non-void function [-Werror=return-type]` but I will leave that for real C(++) devs.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Hi @italic-r, Thanks for the PR.
Can you provide your build log to see on which function you get the `error: control reaches end of non-void function`?

**Comment by fabiencastan** [comment]
I cannot test it right now, but this should fix the issue:
```
inline MSKboundkey_enum convertSign(LPConstraints::eLP_SIGN sign) {
  switch(sign) {
    case LPConstraints::LP_LESS_OR_EQUAL:    // = 1,  // cst (<=) VAL
      return MSK_BK_UP;
    case LPConstraints::LP_GREATER_OR_EQUAL: // = 2,  // cst (>=) VAL
      return MSK_BK_LO;
    case LPConstraints::LP_EQUAL:            // = 3,  // cst (=) VAL
      return MSK_BK_FX;
    case LPConstraints::LP_FREE:
      return MSK_BK_FR;
  }
  throw std::out_of_range("Unknown constraint sign (LPConstraints enum): " + std::to_string(int(sign)));
}
```

**Comment by italic-r** [comment]
That seems to have done it locally. Let's see if CI passes...

Corresponding bug report is #435.

**Comment by fabiencastan** [comment]
Ok, great!
In fact, it's not a false-positive. The default case was just logging a warning without return statement.
The CI builds without MOSEK and I am also building without MOSEK, so I think it's not a gcc-6 specific problem but more the fact that we have not built with MOSEK for a long time and the `-Werror=return-type` was not enabled at that time in cmake.

**Comment by italic-r** [comment]
Would it be more appropriate to discourage using MOSEK? It seems to be a big source of problems for me and last night I forgot to include those libs when I cleaned my cmake config, resulting in a less-painful build with only minor edit.

**Comment by fabiencastan** [comment]
Yes, if you have no specific reason to use it (like making comparisons, etc.), you should skip it.

**Pull request merged**
