### PR TITLE
Replace deprecated basestring with str (Py3)

### PR DESCRIPTION
**Pull request by MmAaXx500**
## Description
In Python3 `basestring` was removed and replaced with `str`. So I replaced them.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Thanks for the PR and sorry for the huge latency.
For full compatibility, we can do:
```
try:
    _ = basestring
except NameError:
    # 'basestring' is undefined, so it must be Python 3
    basestring = (str, bytes)
```
What do you think?

**Comment by MmAaXx500** [comment]
Yes, you are right!
I will change it shortly.

**Comment by fabiencastan** [comment]
We still need to maintain compatibility with python 2.
Could you put the code I proposed at the beginning of the file and continue to use basestring?
This way on python 2 it will find the original basestring and on python 3 basestring will be defined as `(str, bytes)`.

**Comment by MmAaXx500** [comment]
Sorry, I misunderstood what do you mean.
Of course.

**Comment by fabiencastan** [comment]
@MmAaXx500 Thanks for making the PR and not only reporting the issue!

**Pull request merged**
