### PR TITLE
Update cameraSensors.db

### PR DESCRIPTION
**Pull request by Donmiclette**
Please add this to the sensor database. I have tried but it wont save.  

Samsung;Samsung Galaxy A51;26;devicespecification

### CODE REVIEW

**Comment by natowi** [comment]
26 ? are you sure?

**Comment by Donmiclette** [comment]
Good afternoon

     When I Google my brand it says 26mm but it has 4 cameras. I'm new to
this so any assistance and advice would be greatly appreciated.

Donald Miclette

**Comment by simogasp** [comment]
according to 
https://www.kimovil.com/en/samsung-galaxy-a51-5g/camera
your main sensor is a 1/2.25 (Sony IMX582) which has a width of 6.4mm
https://www.deviceranks.com/en/camera-sensor/689/sony-imx582-exmor-rs

I don't know if there is a way through the exif to know which of the 4 camera has been used

**Comment by natowi** [comment]
It´s the main camera, I checked. The other cameras are normally used for tele / macro and/or calculating a depth image for auto focus or other features. Since Meshroom allows only for one sensor/device we declare only the main sensor. Users need to make sure to use the right capturing mode.

**Comment by natowi** [comment]
@Donmiclette you can add _Samsung;Samsung Galaxy A51;6.4;devicespecification_ to your sensordatabase. It will be available for all with the next release.

**Comment by Donmiclette** [comment]
Thank you!

**Review by natowi — APPROVED** [review]

**Comment by Donmiclette** [comment]
Good afternoon,

      I have tried numerous times to add the information to the database
but it still does not work. And that i believe is causing me to get stuck
at Structure From Motion at 39. Not sure what to do here.

**Comment by natowi** [comment]
@Donmiclette now we can not merge the database entry.
Do the imported images have a green icon in the viewer?

**Comment by Donmiclette** [comment]
No, they do not.

**Comment by Donmiclette** [comment]
Just a FYI of what I'm doing. I took a video of my whole house and then
converted the video to images and it ended up being over 26,000 images. So
I added them to the Meshroom to use to make a perfect as much as possible
design i can use for projection mapping this year.. when i load the
pictures i always have a red emblem in left corner. I am new to this so if
anyone can assist if I'm doing something wrong   please let me know.

**Pull request closed without merging**
