### PR TITLE
Update cameraSensors.db

### PR DESCRIPTION
**Pull request by 533online**

### CODE REVIEW

**Comment by fabiencastan** [comment]
Could you put the link to the website where you found this information?

**Comment by 533online** [comment]
on your own

DeviceSpecifications - Mobile device specifications, comparisons, news,
user reviews and ratings <https://www.devicespecifications.com/>

**Comment by natowi** [comment]
The only thing I can find is that it has a Samsung sensor. But no details on the model or size

**Comment by 533online** [comment]
Sorry got my info confuseled. Google store app: DevCheck. Open app in Chuwi
Hi9 Pro scroll over to camera tab,
under 8.0 MP lists Resolution as 3264X2448, Sensor size as 4.63x3.19 mm,
Focal Length 3.5 mm

How accurate that is I cain't say. There's a lot of screwy apps out there,
as this is a free app I see no reason for
them to just make it up. Try it on your own phone and determine accuracy
for yourself.

5.0 Camera has a separate entry.


                                             Jerry Drummond

**Comment by natowi** [comment]
> How accurate that is I can't say

I checked it and it looks good.

In this case the sensor could be a ISOCELL 3H2 (with 3D-BSI, not listed in the Wikipedia entry).
No changes required.

**Review by natowi — APPROVED** [review]

**Pull request merged**
