### PR TITLE
Update cameraSensors.db

### PR DESCRIPTION
**Pull request by Tigwin**
samsung note10+

### CODE REVIEW

**Comment by simogasp** [comment]
Thanks for your contribution!
Can you tell where you get the value and which of the 4 cameras on the Note+ you are referring to?
Is this for the wide-angle one (1/2.5")?

**Comment by Tigwin** [comment]
> Can you tell where you get the value and which of the 4 cameras on the Note+ you are referring to?
> Is this for the wide-angle one (1/2.5")?


When I take a photo with the camera, the phone shows me 3 options, wide angle, normal, and zoom. This is from the normal "middle" option. I don't know how a 4th camera factors in.

**Comment by Tigwin** [comment]
> Thanks for your contribution!
> Can you tell where you get the value and which of the 4 cameras on the Note+ you are referring to?
> Is this for the wide-angle one (1/2.5")?

I just took a bunch of photos with the ultra wide angle lens (earlier I used the standard wide angle lens) and meshroom info says they are also 5.72 ...

**Comment by simogasp** [comment]
Thanks, the normal one should be the wide-angle which is 1/2.55"
I was just wondering where did you find the value of 5.72, because I cannot find the info for a 1/2.55", here
https://en.wikipedia.org/wiki/Image_sensor_format#Table_of_sensor_formats_and_sizes
there is only 1/2.5" which has 5.76 as width. 5.72 seems reasonable but I just wanted to know if you found that in any documentation

**Comment by Tigwin** [comment]
> Thanks, the normal one should be the wide-angle which is 1/2.55"
> I was just wondering where did you find the value of 5.72, because I cannot find the info for a 1/2.55", here
> https://en.wikipedia.org/wiki/Image_sensor_format#Table_of_sensor_formats_and_sizes
> there is only 1/2.5" which has 5.76 as width. 5.72 seems reasonable but I just wanted to know if you found that in any documentation


I'm just loading the images into meshroom and clicking the "info" button for the image. It tells me the sensor size. Is that not going to be accurate?

**Comment by simogasp** [comment]
ah ok I see, is it a field like "CCD width" or similar?

**Comment by Tigwin** [comment]
> ah ok I see, is it a field like "CCD width" or similar?

I don't know anything about it other than I also took photos with my DJI Mini and the sensor info matched in meshroom with what cameraSensors.db had listed for it.

**Comment by Tigwin** [comment]
> ah ok I see, is it a field like "CCD width" or similar?

Here's what meshroom shows:

https://imgur.com/fgoGLRl

**Comment by simogasp** [comment]
Thanks

**Pull request merged**
