### PR TITLE
[Docker] add docker support

### PR DESCRIPTION
**Pull request by simogasp**
Support for docker.

It is based on `nvidia/cuda` image (https://hub.docker.com/r/nvidia/cuda/)

A parameter `CUDA_TAG` can be passed when building the image to select the ubuntu and cuda version. 
For example to create a ubuntu 16.04 with cuda 8.0 for development, use
```shell
CUDA_TAG=8.0-devel
docker build --build-arg CUDA_TAG=$CUDA_TAG --tag alicevision:$CUDA_TAG .
```

In order to run the image nvidia docker is needed https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)
```
docker run -it --runtime=nvidia alicevision:$CUDA_TAG
```

## Implementation notes

* It is based on the cmake script that build all the needed dependencies
* Change introduced in the cmake script to install everything in the same folder (AV and dependencies): the docker will install everything in /usr/local/ so that all the script are immediately available in the PATH.

### CODE REVIEW

**Comment by simogasp** [comment]
@TODO
* maybe remove the `build` directory to limit the size of the image (~4GB...)

**Comment by simogasp** [comment]
@fabiencastan The docker has been tested in different contexts and it seems to work.
We can merge the PR, there are just a couple of decision to take:

* I modified the `INSTALL_DIR` of each target to point to `${CMAKE_INSTALL_PREFIX}` in the cmake script so everything (AV and dependency) is installed on the same root. The drawback is that if for some reason one want to modify lib he needs to uninstall it (cmake uninstall) otherwise it has conflicts during building. But the idea of the script is to make one install for good, not really for development. 

* maybe remove the build directories from the docker to make it lighter?

* add the documentation

* it does not work as an automatic build on docker hub as it seems to deplete all the resources even with -j1

**Comment by fabiencastan** [comment]
Great!
- I'm not a big fan of changing the installation directory. I'd rather use the bundle target at the end. But if you think it's better, I can live with it.
- Yes, we should definitely remove the build folder!
- For docker hub, we will see later and maybe split the build between the main repo and the dependencies.

**Comment by simogasp** [comment]
>I'm not a big fan of changing the installation directory. I'd rather use the bundle target at the end. But if you think it's better, I can live with it. 

I haven't tried yet with the new `ALICEVISION_USE_RPATH` option, but one of the problems was that the libs and bins didn't have the link to the dependencies. Maybe that fixed it

**Pull request closed without merging**
