### PR TITLE
Build OpenCV with FFmpeg on Linux

### PR DESCRIPTION
**Pull request by c-ewing**
## Description

Due to the non-standard install location of FFmpeg during the AliceVision build OpenCV cannot find it. This patch adds FFmpeg to the BUILD_PREFIX of OpenCV to enable the FFmpeg features. 

This builds on the work done in https://github.com/alicevision/AliceVision/pull/1732 by @furbrain and @fabiencastan.

## Features list

- [ ] Fix https://github.com/alicevision/Meshroom/issues/2285

## Implementation remarks

Expanding on https://github.com/alicevision/AliceVision/pull/1732, OpenCV fetches a prebuilt FFmpeg when building for Windows but looks for system libraries when building on Linux.

OpenCV being built without FFmpeg is confirmed by building the Ubuntu docker image and running:
```
$ ./opt/AliceVision_install/bin-deps/opencv_version -v | grep -i ffmpeg
```
Which responds with `NO`.

OpenCV is picky about how external dependencies are specified and it does not support directly specifying install locations. Instead of specifying a location OpenCV's CMAKE uses [`find_package()`](https://github.com/opencv/opencv/blob/64d3111377ef82d73653267d5f924e6afaf966dc/modules/videoio/cmake/detect_ffmpeg.cmake#L9) to find packages. It first looks for Modules in `CMAKE_MODULE_PATH`, then looks within the OpenCV source for Find<Package>.cmake files according to the [CMake Docs](https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature).

This implementation adds the FFmpeg install path to the `${CMAKE_PREFIX_PATH}` of OpenCV, allowing `find_package()` to search in `${CMAKE_INSTALL_PREFIX}` when building.

This change is confirmed by running `opencv_version -v | grep -i ffmpeg`, resulting in `YES`

### CODE REVIEW

**Review by fabiencastan — APPROVED** [review]

**Comment by cbentejac** [comment]
Thanks for your contribution @c-ewing!

**Review by cbentejac — APPROVED** [review]

**Comment by ConejosFritos** [comment]
I am very sorry if the answer to my question appears very obvious to others but I cannot follow how am I supposed to implement this solution, are there any step by step instructions to be found for this implementation?

**Comment by c-ewing** [comment]
Hey there!

I don't have any step by step instructions however the latest Alicevision
docker images should be being built against this change. You can either
pull the images from dockerhub or build the latest Alicevision from scratch
using the docker files provided in the repo (this can take a *long* time).

I'm not sure what your use case is but if you're looking to use this with
Meshroom you'll have to modify your install as there is no version shipping
with these changes.

**Comment by ConejosFritos** [comment]
ok, thank you very much, I was trying out Meshroom for 3d modeling but it appears to not only require a CUDA capable Nvidia GPU which I do not have in my linux Laptop, but also seams incomplete of certain features. I guess I will continue trying different Photogrametry apps for my modeling attempts

**Pull request merged**
