### PR TITLE
[SensorDB] ~100 models added

### PR DESCRIPTION
**Pull request by natowi**
models added and list sorted

### CODE REVIEW

**Comment by fabiencastan** [comment]
Hi,
Sorry for not merging that before!!
Have you used [the script provided in the repository](https://github.com/alicevision/AliceVision/blob/develop/src/aliceVision/sensorDB/sensorDatabaseSort.py) to sort the DB?
It seems that the sort used is not the same and creates many modifications for nothing, like inverting "AgfaPhoto;AgfaPhoto ePhoto CL30 Clik!" and "AgfaPhoto;AgfaPhoto ePhoto CL30".

**Comment by natowi** [comment]
@fabiencastan No, I was not aware of the sorting script

**Comment by fabiencastan** [comment]
Could you re-process your file with the script?

**Comment by fabiencastan** [comment]
Thanks!

**Pull request merged**
