### PR TITLE
Ceres 2 compatibility

### PR DESCRIPTION
**Pull request by fabiencastan**

### CODE REVIEW

**Comment by simogasp** [comment]
what happens to the number of threads for ceres > 2? Is there still a way to set them?

**Comment by fabiencastan** [comment]
http://ceres-solver.org/version_history.html
"Solver::Options::num_linear_solver_threads is deprecated, Solver::Options::num_threads controls all parallelism in Ceres Solver now. Similarly, Solver::Summary::num_linear_solver_threads_given and Solver::Summary::num_linear_solver_threads_used are also deprecated."

@fabienservant : It seems that this api break has been introduced in version 1.14, isn't it?

**Comment by fabiencastan** [comment]
@fabienservant @ahmadhasan2k8: It seems that this api break has been introduced in version 1.14 and not in version 2.0. Should we change the test to "CERES_VERSION_MAJOR < 2 && CERES_VERSION_MINOR < 14"?

**Comment by ahmadhasan2k8** [comment]
@simogasp  So, did it fail in version 1.14? because the current CERES version what I used has [this](https://github.com/ceres-solver/ceres-solver/blob/cd48f83f8d4ff8668c862232eeac9fe1c1d1a02c/include/ceres/version.h)
So, current github Major version is 2. If it fails on version 1.14 then your suggested change should be "CERES_VERSION_MAJOR < 1 && CERES_VERSION_MINOR < 14" instead of "CERES_VERSION_MAJOR < 2 && CERES_VERSION_MINOR < 14"

Thanks

**Comment by simogasp** [comment]
In 1.14 it is still declared but kinda of deprecated (initialized to -1) as we can see in this commit https://github.com/ceres-solver/ceres-solver/commit/3d933750a7dcfec04c6408315caccc5034eaf309#diff-c48e5f42ab7f03f78b8acff2192f0431L121

Then it has been removed in this commit after 1.14
https://github.com/ceres-solver/ceres-solver/commit/cfdc2af28b400a921d7465ab066656d5fafccc7a
which is already is in version [2.0](https://github.com/ceres-solver/ceres-solver/blob/cfdc2af28b400a921d7465ab066656d5fafccc7a/include/ceres/version.h#L34)

So i guess it is safer to set 1.14 as the version from which it is not supported anymore.

Here is the history
https://github.com/ceres-solver/ceres-solver/search?q=num_linear_solver_threads&type=Commits

**Comment by ahmadhasan2k8** [comment]
I see. In that case you might simply run this in the root directory
find ./ -type f -exec sed -i 's/CERES_VERSION_MAJOR < 2/CERES_VERSION_MAJOR < 1 && CERES_VERSION_MINOR < 14/' {} \;
It should ideally replace the string throughout (if I got the spaces and everything right in the string, you might wanna check that in the branch you are working on) and easier for a quick test.

Not sure if find and sed will work on windows directly but in a linux machine it should.

**Pull request closed without merging**
