### PR TITLE
[cmake] Modern cmake for Alembic

### PR DESCRIPTION
**Pull request by simogasp**
connected to alicevision/AliceVision#252

Use modern cmake to find/link Alembic.
It works only properly for versions >= 1.7 from the github repository

Also add Alembic in CI on travis.

@gregoire-dl @fabiencastan Incidentally, it also fixes the broken pimpl implementation for AlembicExporter: the pimpl was introduced to hide the implementation and the direct dependencies from Alembic, ie simply put, avoiding includes to Alembic inside the *.hpp.
So instead of having another alembic pameter `parent` in `addCamera()`, I moved the implementation in the pimpl structure and reverted the old API.

### CODE REVIEW

**Comment by simogasp** [comment]
waiting for alembic/alembic#128, anyway it works fine if alembic is built as dynamic lib

**Comment by simogasp** [comment]
@griwodz can you test it, it works on mac and in travis we don't have alembic installed.

**Comment by yann-lty** [comment]
Tried it on Windows (locally merged with my `fix_winbuild` branch) and it works with Alembic 1.7.5 (current version in vcpk).

**Comment by simogasp** [comment]
@yann-lty if it works even on windows there is no reason it won't work :-D

**Comment by simogasp** [comment]
@fabiencastan @gregoire-dl 
It can be reviewed and merged now.
I started to diverge and fixing some unrelated stuff in sensorDB, i'll make another PR just for that.
The last two commits, though, are not alembic related but they fix 2 compilation issues of clang and it would be better to add them asap, so i kept them here.

**Comment by griwodz** [comment]
@simogasp I failed to answer your request: builds fine with Alembic 1.7.5 on Ubuntu 16.04.

**Comment by simogasp** [comment]
great, thanks!

**Comment by simogasp** [comment]
can we merge it?

**Comment by fabiencastan** [comment]
We have just started to build alembic-1.7 last Friday, we will test tomorrow to see if we can do the switch in production.

**Pull request merged**
