### PR TITLE
Fix Windows build

### PR DESCRIPTION
**Pull request by yann-lty**
## Description
Fix Windows build.

## Features list

- [X] Fix `M_PI` undeclared identifier
- [X] Fix compilation error on a double*Mat3 operation
- [X] Use signed ints for openMP loops
- [X] Use streampos when evaluating os.tellp() result
- [X] Support boost >= 1.66 (dropped support of deprecated empty_deleter)
- [X] Fix missing includes
- [X] Misc: Enable folder in Visual Studio

### CODE REVIEW

**Comment by simogasp** [comment]
I made an appveyor here https://github.com/simogasp/AliceVision/blob/ciAppveyor/appveyor.yml
but the version of openimageio on vcpkg is too old and makes everything fail.

**Comment by yann-lty** [comment]
I'm planning to fork `vcpkg` in the AliceVision organization to make the appropriate changes for everything to work; and submit PRs for updating libraries versions (`openimageio` and soon `geogram`). Does this sound like a good option to you ?

**Comment by simogasp** [comment]
sounds good

**Comment by yann-lty** [comment]
vcpkg with oiio 1.8.8 available here:
https://github.com/alicevision/vcpkg/tree/oiio_update

**Pull request merged**
