### PR TITLE
Fix doc install

### PR DESCRIPTION
**Pull request by simogasp**
## Description

Some fixes for INSTALL.md

## Features list

- [X] removed obsolete info
- [X] added list of required and optional dependencies

### CODE REVIEW

**Comment by griwodz** [comment]
Simone, I branched "newAlembicDependency" from here. I installed a newer Alembic where find_package(Alembic CONFIG) works and all the old ABC stuff doesn't, but as far as I can understand there is no way I could set(ABC_LIBRARIES "PRIVATE Alembic::Alembic") and keep the old linker strings. Is it backwards compatible to simply have both in target_link_libraries ???

**Comment by simogasp** [comment]
* if u add `CONFIG` then we are not back-compatible with the old findAlembic method. Which is fine with me but I don't know if the rest of the folks have a problem with that (it means they have to upgrade to a recent >=1.7 version

* If u look at the PR #265, i left `PRIVATE` as a comment, because u cannot mix old style cmake with the new `target_link_libraries` stuff. So to do it properly we should add PRIVATE and PUBLIC (or INTERFACE) everywhere, for all targets.

**Comment by simogasp** [comment]
> If u look at the PR #265, i left PRIVATE as a comment, because u cannot mix old style cmake with the new target_link_libraries stuff. So to do it properly we should add PRIVATE and PUBLIC (or INTERFACE) everywhere, for all targets

Ok no, my bad, it seems that it has been done with the major refactoring. So we can just add PRIVATE Alembic::alembic to the relevant `target_link_libraries`. That on the other hand will break once and for all the old way of getting alembic. I'm all in for switching to the new version and forget the past.

**Comment by simogasp** [comment]
also, you can get it from homebrew (https://github.com/Homebrew/homebrew-science/blob/4bfbd556d99fbf7ef4f9c92f91ab129b91ce52fe/alembic.rb) and vcpkg for windows.

**Comment by yann-lty** [comment]
+1 for modern cmake Alembic, as this is indeed required when using vcpkg :)

**Comment by simogasp** [comment]
I will upgrade the pending PR as it is not mergeable anymore and see what happens

**Comment by griwodz** [comment]
I like the idea of dropping support for pre-1.7 Alembic. I'll adapt my changes and make a pull request newAlembicDependency -> fixDocINSTALL

**Comment by simogasp** [comment]
@griwodz it's all done in #265  now, i even add the travis support to compile with alembic. Also, more importantly that pr it also fixes a broken implementation of the Alembic{In,Ex}porter

**Comment by griwodz** [comment]
Oh, I'm all for merging #265  it in that case.

**Pull request merged**
