### PR TITLE
Add entry to cameraSensors.db

### PR DESCRIPTION
**Pull request by KenwoodFox**
Add Moto Z (2) to camerasensors.db.

## Description
Added a missing entry to cameraSensors.db
This is my first time doing this.

## Implementation remarks

On each installation of meshroom I add this to the DB file so it functions with my phone, it would be nice if this were part of the standard program.

### CODE REVIEW

**Comment by simogasp** [comment]
Hi, thanks for contributing!
What is the exact model of the phone? Can you give a link pointing to it?

**Comment by KenwoodFox** [comment]
Thanks so much :3 hope I'm doing ok.
I believe its officially called a Moto Z2 Force, but the presented model name in android and in the camera metadata is Moto Z (2).
I did not find a link on Motorola's website, interesting, but i did find a sellers link on some, [site](https://gadgets.ndtv.com/motorola-moto-z2-force-4232).

**Comment by simogasp** [comment]
According to this
https://www.devicespecifications.com/en/model/76ab44ae
it is a 1/2.9" sensor which translates into a width of 4.98.
How did you come up with 6.29, can you give a link or an example?

**Comment by KenwoodFox** [comment]
Oh, Perhaps my math was wrong then.
Maybe this is why my meshroom projects require so much afterwork.
Thank you for doing the calculation. I don't remember where i got 6.29 from, i think i read the sensor gross dimension off a manufacture's page and then calculated its width from that but i don't have a link.

**Comment by fabiencastan** [comment]
Is it ready for merge? It's still named WIP in the title.

**Comment by KenwoodFox** [comment]
Oh, right i didn't know i needed to change that.

**Review by fabiencastan — APPROVED** [review]

**Comment by fabiencastan** [comment]
Have you tested it with the new value? Does it work fine? Does it change the results regarding your previous value?

**Pull request merged**
