### PR TITLE
Merge mvsData image and pixel classes with what's in image module

### PR DESCRIPTION
**Pull request by p12tic**
This PR cleans up `mvsData` to not have its own image and pixel representations and reuse image module instead. As asked by Fabien, all changes are included into a single PR. All commits are atomic and compile cleanly, so if we decide we want to merge the PR in parts, it can be split at any point.

Image IO code could potentially be cleaned up even more, but this requires replacing `std::vector<T>` representation with `Image<T>` in a number of places and this seemed to be much larger scope than would be reasonable. 

One perhaps interesting change was that we have separate notion of OIIO colorspaces - they don't map directly to EImageColorSpace as we support color spaces that OIIO does not support and vice-versa. This is handled by separate set of functions to convert and manage OIIO colorspace names.

### CODE REVIEW

**Comment by fabiencastan** [comment]
https://github.com/alicevision/AliceVision/pull/1251 merged. Needs a rebase.

**Comment by p12tic** [comment]
@fabiencastan Rebased, thanks.

**Comment by p12tic** [comment]
I've removed last 5 commits out of this PR because they should be part of a subsequent PR that reduces the number of ways we represent an image (i.e. replace `std::vector<T>`+width+height with `Image<T>`).

**Review by gregoire-dl — APPROVED** [review]
Thank you for the great contribution! I double checked the code and tested it, everything works fine.
It would be great if you could also fix the `multiBandBlending` sample using the `image::Image` class and `imageAlgo::laplacianPyramid` function. The sample was not built before, but it would be nice to restore it.

**Comment by p12tic** [comment]
@gregoire-dl I have resurrected the `multiBandBlending` sample, it compiles fine, didn't check whether it runs, but I didn't do any hacks, so there shouldn't be any hard to fix problems left.

The resurrected sample requires even more pending changes than there are in this PR, so I haven't created a PR yet. I will do soonce all of that depending code is merged.

**Comment by p12tic** [comment]
Thanks Fabien.

**Pull request merged**
